---
title: "Blog Ideas"
author: "Galen Seilis"
---

Some ideas for blog posts:

---

How to choose software tools with respect to development effort and the Turing tar pit.

---

Asychronous programming is not required for DES, but is it better?

---

All data is spatiotemporal data, and we often neglect that fact. It has never been so easy to collect the time and location of measurements. Some measurements are paired to sets of time and space rather than individual points.

---

BCData --> Get some geospatial data --> Load data using Geopandas --> Plot using Folium.

---

Ibis integration with Kedro example.

---

UML used to be considered a tool for designing programs. That purpose has been mostly abandoned in modern software development. The primary use case for UML IMO is to go the other way; generate UML from code. 'Sometimes' a UML diagram can provide a useful bird's eye pictureo of the structure of a program, which can help a programmer unfamiliar with some code get up and running.

---

Go over the common software design patterns, showing code examples of each one.

- https://en.wikipedia.org/wiki/Software_design_pattern
- https://en.wikipedia.org/wiki/Design_Patterns

---

Adversarial learning of simple probability distribution parameters. Could make for a good explainer of aversarial learning. Not sure if it is really better than other parametrization approaches though, but it is at least generative by construction.

---

Discuss the time-to-event vs time sweeping in simulation. The former tends to produce faster programs when the event density is relatively low. The latter tends to be faster when high event density (in time) is high and local state updates can be parallelized.

---

Asyncio example of file IO.

---

Chaos isn't just about high sensitivty to initial conditions. It is also about topological transitivity and density of orbits. IMO, the topological transitivity might be the most important property. Topological mixing is a special case of topological transitivity which may be easier to explain.

---

Quadrant rule in BC silviculture assumes a type of spatial homogeneity within a plot. Even if a plot is ostensibly a "cedar carpet", the density may not be truly uniform. A broader set of principles based on partitioning the plot and using symmetries generalizes the quadrant rule.

---

There is/was a fixed percentage agreement required between a silviculture surveyor and an auditor. I recall a professional forester assuring me that this ensures a reasonable expectation of agreement bewteen surveyor and auditor because the percentages "scale up". They could be right, but I'm skeptical about this. 

As the number of trees increases we should expect the variance of the counts to increase until even highly-skilled professionals will tend not to agree with each other within that fixed percentage agreement. Under an assumption of statistical independence we can easily show that this is true. Whether such a number of trees is counted in practice is not known to me, and mathematically it depends on the parameters.

---

What distribution do the counts within a silviculture plot follow?

I expect that the number of natural regen trees within an untreated area (i.e. not planted) follows an inhomogenous Poisson point process for the number of trees. Recently-planted trees should follow a probability distribution that is close to uniform (but not exactly uniform because it is more like a grid). 

Regardless of the number of trees, the number of trees that a suveyor counts will count has both false positives and false negatives. A first approximation could be a binomial distribution with some probability of sucessfully counting each tree. But not all trees are equally easy to spot, motivating us towards something like a Poisson binomial distribution. This approach may be more realistic, but if we can get away with a binomial likelihood with a Beta distributed prior on the probability of detection that might be more feasible. Maybe we could even show that some operation like marginalization gives us the binomial distribution from the Poisson binomial.

Once we have chosen a suitable mathematical model, we could show 

---

Marginal distributions are underrated, but despite their simplicity they get a bad rep. People often feel the need to stratify their variables, thereby conditioning the distribution they've interested in. This creates higher variance estimates and does not take any advantage of pooling. Partial pooling is a great way to go, but I think there are sometimes simpler analyses based on the marginal distributions that answer the same questions. Complete pooling is sometimes an appropriate modelling choice.

---

Explore a sequence of location-composed exponential distributions. Although each step is memoryless, the overall stochastic process is not.

---

Explore Kedro integration with Quarto.

---

Asynchrony vs concurrency in programming.

---

Implement metropolis hasting algorithm from scratch in Rust/Python.

---

The fastest discrete event simulation are not those which are developed within a framework that provides a huge number of features, or provide abstractions to generalize across huge spans of use cases. Rather, it will be the implementations that take the greatest advantage of speciality rather than generality. To know what you can assume and lean into that will produce a faster simulation product. This is one argument in favour of bespoke simulations over framework tools or enterprise development software.

- Give an example of a FIFO M/M/1 queue implementation using a framework tool (e.g. Ciw) vs a minimumal implementation in Python.
- Also show an implementation in Rust to further emphasize the point that being able to assume data types is an example of the overall notion that specialty can provide better performance.

There are, of course, downsides to specialized softare. They can sometimes be less configurable out of the box. If what you need for a given project actually is a large multifeatured tool, then writing it yourself might only provide minor benefits.

I think that when you really have no idea what you need, which often happens when you're building a product the first time, going for a framework tool that is highly generalized and flexible makes sense for obtaining and MVP. But you're product will plausibly be slower, and possibly more complicated under the hood than needed. 

If the required feature set stabilizes, then it may be time to look at writing something that is specialized to solve the problem **well** rather than solve it generically.

---

Overview of important Git features.

---

Causal structure of discrete event simulation from a Pearlian causal inference point of view.

---

Create an example hybrid DES system when parts of the smooth state inform the discrete system and *vice versa*.

---

Kedro catalog can contain "metadata" which can be used to put any information you want into it. It is intended by the Kedro devs for plugins, but you can really put any info you want there. This includes things like annotations of variables, which can be programmatically loaded later to provide glossaries of terms and similar things.

---

Provide an example statistical model of service completion rate where the number of servers is an integer and the completion rates are statistically dependent. The purpose of this exercise is to provide a statistical model that allows servers to be cooperative or competitive in service completion rates, which "competition" could just mean negatively related rates, without modelling individual servers as data structures in a simulation.

A first approximation could look like this. Suppose a total service comletion rate $\mu$, which can be decomposed into the rates for each server:

$$\mu := \sum_i \mu_i$$

where $\mu_i$ is an individual server's service completion rate. However, this misses having some form of statistical dependence. To get that we can assume a multivariate log-normal distribution over the individual server's rates.

---

Numba doc examples vs Rust.

---

CuPy examples vs Rust.

---

Bayesian graphlets analysis.

---

Writing software to be highly general is an approach to managing uncertainty about the future use cases. It lowers the risk of later finding that you need to extend the software, and optimistically hopes that it lowersthe risk of later finding that you need to extend the software when that is difficult.

In a sense the number of features that are implemented prospectively without a planned usage is a measure of how little the developers actually know about the software they need to build. Sometimes 

One of the alternatives to writing highly generalized code is to write code to be extensible rather than general.

The primary downside of aiming for generality is the up-front development effort. You can go to great lengths to create a majestic cathedral when all you needed was a tent.

A secondary downside is the performance of the software itself. While I would not take it as an absolute rule, the tendency I have observed is that highly generalized software (e.g. bloated with features) is slower than specialized software.

---

Give an example of using Ziggy PyDust.

- https://github.com/spiraldb/ziggy-pydust

---

Implement reservoir sampling based on algorithms on Wiki: https://en.wikipedia.org/wiki/Reservoir_sampling


---

Compare SciPy and PyMC.

| SciPy | PyMC |
| --- | --- |
| maximum likelihood estimation | full posterior and posterior predictive sampling |
| mostly designed for simple distribution | designed for custom distributions |


While SciPy does support some multivariate sampling tools, such as the mutlvariate normal distribution, it isn't out-of-the-box well-suited to the typical multivariate distributions we can expect from real data. Often the strategy I have seen taken with SciPy is to stratify the data in such a way that each grouping in the data follows a nice family of distribution. That approach introduces a tradeoff of not pooling shared information about the statistical populations. 

PyMC's largest downside on a given problem for which SciPy could also be used is that it is a more complicated process. SciPy provides relatively quick fitting and sampling. 

SciPy is not well-suited to custom probability distributions. Its underlying fitting methods using inverse transform sampling which only works when the CDF is invertible. Furthermore, it will attempt to use the CDF in an optimization problem to find inverses numerically. That's smart from a math point of view, but it is computationally inefficient in practice.

PyMC is a relatively easy win for mixed models. If you have various grouping in the data and you think each population is from the same family of distribution, differing only in the parametres, then PyMC's `coordinates` makes that easy. More complicated structures are also possible.

I tried to develop some more complicated models using SciPy's distributions combined with its optimization library. I found that mixtures of gamma distributions are particularly tricky, and it wasn't uncommon for the modelling approach to be revised multiple times.

PyMC models can sometimes sample poorly, and there is likewise a whole bag of tricks to refine the model or sampling or data to improve its performance. However, I noticed that it does mixtures quite well whereas I have had "mixed results" (pun intended) with SciPy.

SciPy being based on a maximum likelihood estimation (MLE) approach means that it assumes that the data was sampled from the likelihood distribution. In this approach the family of distributions is assumed and we take the view that it is just a matter of finding the specific parameters.

PyMC being primarly based on full posterior inference means something very different. The data does not need to be seen as a sample from the likelihood at all! The posterior is defined via Baye's theorem to be proportional to the product of the likelihood of the data and the prior. That is, the likelihood refines the prior using the data.

---

Implement the various statistical and DES models you have seen in healthcare.

---

Prepare some posts on uncertainty quantification.

---

Model a stochastic matrix by having each row be a multinomial logistic regression.

---

Model a stochastic matrix by having each row follow a Dirichlet distribution.

---

Explain what a compact topological space is, and why it matters as a modelling assumption.

---

Python exceptions should be preferentially used for exceptional behavior.

---

Provide an example of using Nelsie.

---

Explain how I think about outliers and anomalies. 

Essentially two types: 
- Rare events
- Very different events
    - "One of these things is not like the other" game.
    - This might eventually be the same as the rare events when taken under the certain light.

---

Implement various DES example using the Hades Python package.

https://ki-oss.github.io/hades/

--- 

Implement various DES examples using Python coroutines.

---

Show a modelling example where it would be difficult to model in terms of sampling from the marginal distributions. Discuss the potential consequences for discrete event simulation.

---

Discuss the usage of popularity as a measure of software quality.

AFAIK the only context where the popularity might be invoked is to make an argument that a given tool should be used because it is popular, or at least more popular than some alternative.

When you're in some kind of mode of work where you have to make rapid decisions it makes sense to use heuristics. I don't think that context usually applies for selecting software. Further, I don't think that using popularity as a heuristic is all that reliable and it would make the world of software pretty awful if we all just looked to the most popular tool as the tool to use. That's because the popularity itself would just be due to preferential attachement effects and not due to the quality of the software at all. 

I will say that popular software has often gotten "something" right. Sometimes it is obvious what that is (e.g. Ruff's static analysis is fast). Sometimes it isn't obvious. Sometimes it isn't the software itself but rather that it arrived on the scene early enough to have a big adoption advantage.

---

Homomorphism between causal graphs and computation graphs on random variables.

---

Go over the mathematical formalism of DES. I think it might be Zeigler that is a good reference for this.
- Discrete event system specification
- Timed-event system
- Transition system

---

Programmer have to practice building thing in order to learn how to build great things. But organizations often do not want you to build and rebuild the product multiple times to get it right. Iteratively rebuilding can be perceived as a source of unecessary cost. In there lays a trade off. If you don't allow your programmers to iteratively rebuild systems then they will not get the experience to build that particular system in a great way. But if you allo your programmers to iteratively rebuild systems then it will take more time and cost more. Prototyping can offer some compromise, but I expect that overall there is a Pareto front.

Programmers can learn skills and concepts that transfer to future projects, which alleviates some of this problem.

The business should also understand that if they want to produce the various best thing of some type that it is going to require substantial cost, one way or another.

---

Contrast event-based DES from process-based DES. This distinction is commonly made, but rarely defined. Providing an explanation of what these terms mean could be beneficial.

---

Explore whether detailed balance in MCMC can be generalized.

---

Write a Rust program which creates and occupies a SQL DB, and then queries from it.

---

Write a Rust program which loads a CSV file.

---

Write a Rust program which loads a yaml file.

---

Run Mathematica in Quarto. Maybe use the Python Wolfram client package.

---

Explain what performance ratcheting is.

In common parlance, performance ratcheting is when the expectations for an employee's performance increase endlessly. This requires some mathematical terminology to make precise.

Suppose a cumulative increasing function is applied to the history of performance of the employee, which is used to define what is expected (but not necessarily the mathematical expection) of the employee's performance.

Examples:
- maximum
- mean

It might be worth exploring what is better than this.

---

Write the mathematics and PyMC code for an autoregressive model in which the time lags used follow a discrete probability distribution. That is, which time lags are used is random.

---

Simulate random delayed differential equations with PyMC.

It might require integration with other packages.
- ddeint
- pydelay
- jitcdde
- scipy (there are some examples on stack overflow)

---

Show an example of using ordinal regression to model count data.

The advantage of this approach is that it can take on a wide variety of shapes that classic count distributions cannot.

AFAIK, this would have the disadvantage of being bounded from above. This would mean choosing a finite number of bins. The largest bin would actually need to represent "X or greater", which means the upper bin would not really act like a count. I wonder if Frank Harrel or some other statistician has found something nicer than this.

---

Does using asynchronous programming make the locality of behaviour better or worse?

---

Using the stack tracing tool in Python, implement a tool which collects the file and line number as a program executes. This can be visualized as a heatmap where the row of the heatmap is the computation step and the column indexes the files that are used. The entries are the row number of the file for the instruction being executed. From there we can define some metrics for how much we're jumping around.

---

Give an introduction to interval arithmetic.

---

Give a worked example of using Samuelson's inequality.

https://en.wikipedia.org/wiki/Samuelson%27s_inequality

---

Give an example of Bayesian non-negative polyadic decomposition using PyMC.

Provide similar, but probabilistic, diagrams similar to those shown by Kolda: https://www.youtube.com/watch?v=L8uT6hgMt00

---

Show an example of Bayesian discrete event simulation where the DES is occurring within the...
