---
title: "PyMC vs SciPy"
author: "Galen Seilis"
date: "2023-08-10"
categories: [Python, PyMC, SciPy]
draft: true
---

I got a request to compare SciPy's way of fitting and sampling of distributions with that of PyMC. In this post I'll make some comparisons based on theory and computational examples.

## Theory

There are some theoretical differences between what is happening in SciPy and PyMC, but the theory also comes from outside of these tools.

It is tempting to think that SciPy is simply frequentist and PyMC is simply Bayesian, but it isn't quite that simple. Where frequetists fundamentally differ with Bayesians has to do with how probability is interpreted, not whether we make explicit use of Bayes' rule.

And yet in pracice you'll find that Bayesians will tend to use PyMC, as it was intended, because often frequentists are unwilling or unable to say what their base rate should be. I have even seen people state that if a parameter is treated as a random variable then it is Bayesian. That's not strictly true, but practically it is substantially diagnostic.

## Tradeoffs

When you have a simple model to sample and/or fit from, and you have a large dataset, then SciPy is an appealing option. I have found that PyMC involves more code in the simplest cases.

However, in my experience so far I have had less difficulty in building complex models using PyMC than I have using SciPy's `rv_continuous` class, or similarly writing more custom code to take care of fiting more comlicated models. Also, SciPy doesn't have `fit` methods for discrete random variables, although it does have a variety of other useful methods in its `rv_discrete`.

While there's nothing that guarantees this empirical induction, I find that there is a tendency for PyMC to offer more flexibility in modelling. Like SciPy, it provides classes to define custom probability distributions. SciPy does not give explicit support to building complicated models such as structural equation models or hierarchical models, but it is possible to develop such models.

Sources:
- https://www.pymc.io/projects/docs/en/stable/api/distributions/generated/pymc.Flat.html
- https://www.pymc.io/projects/docs/en/latest/api/distributions/generated/pymc.HalfFlat.html
- https://discourse.pymc.io/t/what-does-pm-flat-really-do/14483
- https://discourse.pymc.io/t/is-the-mode-of-a-parameter-in-a-model-with-only-pm-flat-priors-a-maximimum-likelihood-estimate/14490
- https://stackoverflow.com/questions/78536889/how-to-implement-a-mixture-of-gamma-distributions-in-python-without-bayes
- https://stats.stackexchange.com/questions/648090/is-there-a-likelihood-penalization-or-improper-prior-to-remove-bias-of-estimat

