---
title: "A Critique of the Scalability of Kedro"
author: "Galen Seilis"
date: "2024-09-29"
toc: true
categories: [Python, Kedro, Scalability]
draft: true
---

# Introduction

In this post I give some critique of the scalability of Kedro. I happen to like Kedro, its plugin ecosystem, and the welcoming and helpful community. However, I don't like leaving tools I enjoy without some degree of reflection or critique.

# Computational Scalability

Suppose you want to a function `foo`, representing some arbitrary set of Python instructions, on a fixed input `x`.

A straightforward approach is to just call `foo`:

```python
foo(x)
```

# TODO: Produce an example pipeline for some choice of 'foo'

There will always exist a `foo(x)` such that for a given set of hardware constraints will be computable without Kedro but not computable with Kedro.

We never get function calls and additional objects in memory for free. This is one of the lurking problems with aiming for generality in programs.

The more nodes we have, the more overhead.

# TODO: Example of generating DAGs that run some function (e.g. `def identity(x): x`):w

# TODO: Research and discuss how to deal with files that are too large to fit into memory. How would Kedro deal with this?

Kedro also does a lot of file IO. Having the 

# Project Visualization

I think that Kedro's visualization plugin (Kedro Viz) can improve the experience of a developer coming onto a new project who wants to get a bird's eye view. 

[*"Graphical perception is the human capacity for visually interpreting information on graphs and charts."*](https://en.wikipedia.org/wiki/Graphical_perception). There are *many* rules and aphorisms that have been proposed for how to ensure good visualisations. What makes a visualization 'good' depends on your goals, such as the emphasis of being persuasive rather than highly informational. With Kedro Viz the use case I envision is primarily to be informative.

One of the "golden rules" of visualizations is to keep them simple. That's where Kedro has an eventual scaling problem.

::: {.callout-note}
# Downscaling

While I am primarily concerned in this post about 'upscaling', I have a concern about downscaling. For sufficiently small workflows not much is added in visualizing what you could easily see as a handful of instructions in a script.
:::


While Kedro Viz is capable of visualizing very complicated pipelines, its practical benefit eventually diminishes as the diagrams become highly complex. The computational scalability of Kedro Viz far outstrips the human ability to benefit from it.

# Project Complexity

This is where Kedro has the best scalability properties, if you're careful. The data sources, node IO, and pipelines themselves are required to have names. If this is done well then I think Kedro can keep a rather complicated

Having naming conventions can help with ensuring some level of regularity in what names exist. In some cases it may be able to define the naming rules algorithmically, thus allowing further automation in the creation and searching of complex Kedro projects.

# Conclusions

While we examined Kedro in this particular 
