project:
  type: website

website:
  description: "A blog by a technology and math enthusiast!" # Like we have not seen that before.
  site-url: https://galenseilis.github.io/blog/
  title: "Galen's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/galenseilis
      - icon: bluesky
        href: https://bsky.app/profile/galen-seilis.bsky.social
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



